export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES';
export const PAGES_LOADED = 'PAGES_LOADED';

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS';
export const POSTS_LOADED = 'POSTS_LOADED';
//CUSTOMERS
export const STORE_FETCHED_CUSTOMERS = 'STORE_FETCHED_CUSTOMERS';
export const STORE_FETCHED_CUSTOMERS_ERROR = 'STORE_FETCHED_CUSTOMERS_ERROR';
export const SEARCH_CUSTOMERS = 'SEARCH_CUSTOMERS';
export const SEARCH_CUSTOMERS_ERROR = 'SEARCH_CUSTOMERS_ERROR';
export const ORDER_CUSTOMERS = 'ORDER_CUSTOMERS';
export const ORDER_CUSTOMERS_ERROR = 'ORDER_CUSTOMERS_ERROR';
export const STORE_FETCHED_CUSTOMER = 'STORE_FETCHED_CUSTOMER';
export const STORE_FETCHED_CUSTOMER_ERROR = 'STORE_FETCHED_CUSTOMER_ERROR';
export const CREATE_CUSTOMER = 'CREATE_USER';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';

//PRODUCTS
export const STORE_FETCHED_PRODUCTS = 'STORE_FETCHED_PRODUCTS';
export const STORE_FETCHED_PRODUCTS_ERROR = 'STORE_FETCHED_PRODUCTS_ERROR';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
export const ORDER_PRODUCTS = 'ORDER_PRODUCTS';
export const ORDER_PRODUCTS_ERROR = 'ORDER_PRODUCTS_ERROR';
export const STORE_FETCHED_PRODUCT = 'STORE_FETCHED_PRODUCT';
export const STORE_FETCHED_PRODUCT_ERROR = 'STORE_FETCHED_PRODUCT_ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

// AUTH User
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
//SIDEBAR
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
//Lang
export const SET_LANGUAGE = 'SET_LANGUAGE';
